---
- name: php-fpm
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      openssh_keypair:
        path: /tmp/id_ssh_rsa

    - name: create /var/www/ timestamp directory
      file:
        dest: "/var/www/"
        state: directory
        owner: www-data
        group: www-data
        mode: 0700

    - name: add directory to safe directory config
      command: git config --global --add safe.directory /var/www

    - name: Clone billabear
      git:
        dest: "/var/www"
        repo: https://github.com/billabear/billabear.git
        depth: 1
        clone: yes
        version: latest
        key_file: /tmp/id_ssh_rsa
        accept_hostkey: yes

    - name: Add yarn Apt signing key, will not download if present
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
          repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
          state: present
          update_cache: yes

    - name: Add yarn sources list
      become: yes
      lineinfile: >
          line="deb https://dl.yarnpkg.com/debian/ stable main"
          dest=/etc/apt/sources.list.d/yarn.list
          state=present
          create=yes

    - name: Add ondrej/php
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

    - name: install packages
      apt: 
        update_cache: yes 
        state: latest
        name: [
          'yarn',
          'software-properties-common',
          'nodejs',
          'php8.4-dev', 
          'php8.4-cli', 
          'php8.4-curl', 
          'php8.4-dom', 
          'php8.4-intl', 
          'php8.4-xml', 
          'php8.4-mbstring', 
          'php8.4-zip', 
          'php8.4-redis', 
          'php8.4-mysql', 
          'php8.4-pgsql', 
          'php8.4-amqp', 
          'php8.4-mongodb', 
          'php8.4-gd',
          'php8.4-maxminddb',
          'php8.4-raphf',
          'php8.4-http',
          'php8.4-apcu',
           
          'php8.4-fpm', 
          'wkhtmltopdf'
          ]


    - name: Change permissions
      file:
        dest: "/var/www/"
        state: directory
        owner: www-data
        group: www-data
        mode: 0700
        recurse: yes

    - name: Make public writable (?)
      file:
        path: /var/www/public
        state: directory
        recurse: yes
        mode: '0777'

    - name: Copy file with owner and permissions
      copy:
        src: /tmp/env
        dest: /var/www/.env.local
        owner: www-data
        group: www-data

    - name: install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - composer:
        command: install
        working_dir:  "/var/www"
      become: yes
      become_user: www-data

    - name: install yarn
      command: yarn install
        chdir="/var/www"

    - name: install encore
      command: yarn encore production
        chdir="/var/www"

    - name: Make cache writable
      file:
        path: /var/www/var
        state: directory
        recurse: yes
        mode: '0777'          